name: maven-release

on:

  push:
    tags:
      - '*'

jobs:

  release:

    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up java environment
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
          server-id: ossrh
          server-username: OSSRH_USR
          server-password: OSSRH_PWD
          gpg-private-key: ${{ secrets.MAVEN_KEY }}
          gpg-passphrase: MAVEN_PWD

      - name: Release version to ossrh
        env:
          OSSRH_USR: ${{ secrets.OSSRH_USR }}
          OSSRH_PWD: ${{ secrets.OSSRH_PWD }}
          MAVEN_PWD: ${{ secrets.MAVEN_PWD }}
        run: mvn --batch-mode
          --activate-profiles release
          -Drevision=${{ github.ref_name }}
          deploy
